version: '4'
services:
  db-cats:
    image: postgres:12
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cats-api