apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-api
  labels:
    app: cats-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats-api
  template:
    metadata:
      labels:
        app: cats-api
    spec:
      containers:
        - name: cats-api
          image: xixajzlelshii76bhcr0zztas1k4ja/cats-api:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_HOST
              value: 192.168.55.102
            - name: spring.mvc.servlet.path
              value: /cats-api
            - name: SPRING_ADMIN
              value: http://spring-admin/spring-admin